# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'radio_group.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_rg(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1006, 676)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(270, 104, 130, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(270, 192, 66, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(270, 280, 74, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(270, 368, 120, 17))
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(280, 520, 361, 25))
        self.pushButton.setObjectName("pushButton")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(522, 368, 124, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButton_8 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_8.setObjectName("radioButton_8")
        self.Dynamixel_head = QtWidgets.QButtonGroup(Form)
        self.Dynamixel_head.setObjectName("Dynamixel_head")
        self.Dynamixel_head.addButton(self.radioButton_8)
        self.horizontalLayout_4.addWidget(self.radioButton_8)
        self.radioButton_7 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_7.setObjectName("radioButton_7")
        self.Dynamixel_head.addButton(self.radioButton_7)
        self.horizontalLayout_4.addWidget(self.radioButton_7)
        self.widget1 = QtWidgets.QWidget(Form)
        self.widget1.setGeometry(QtCore.QRect(522, 280, 124, 25))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton_5 = QtWidgets.QRadioButton(self.widget1)
        self.radioButton_5.setObjectName("radioButton_5")
        self.realsense = QtWidgets.QButtonGroup(Form)
        self.realsense.setObjectName("realsense")
        self.realsense.addButton(self.radioButton_5)
        self.horizontalLayout_3.addWidget(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(self.widget1)
        self.radioButton_6.setObjectName("radioButton_6")
        self.realsense.addButton(self.radioButton_6)
        self.horizontalLayout_3.addWidget(self.radioButton_6)
        self.widget2 = QtWidgets.QWidget(Form)
        self.widget2.setGeometry(QtCore.QRect(522, 192, 124, 25))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.widget2)
        self.radioButton_3.setObjectName("radioButton_3")
        self.Lidar = QtWidgets.QButtonGroup(Form)
        self.Lidar.setObjectName("Lidar")
        self.Lidar.addButton(self.radioButton_3)
        self.horizontalLayout_2.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.widget2)
        self.radioButton_4.setObjectName("radioButton_4")
        self.Lidar.addButton(self.radioButton_4)
        self.horizontalLayout_2.addWidget(self.radioButton_4)
        self.widget3 = QtWidgets.QWidget(Form)
        self.widget3.setGeometry(QtCore.QRect(522, 104, 124, 25))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget3)
        self.radioButton_2.setObjectName("radioButton_2")
        self.Dynamixel_motor = QtWidgets.QButtonGroup(Form)
        self.Dynamixel_motor.setObjectName("Dynamixel_motor")
        self.Dynamixel_motor.addButton(self.radioButton_2)
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(self.widget3)
        self.radioButton.setObjectName("radioButton")
        self.Dynamixel_motor.addButton(self.radioButton)
        self.horizontalLayout.addWidget(self.radioButton)

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.bringup)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.radioButton_2, self.radioButton)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Dynamixel (motor) "))
        self.label_2.setText(_translate("Form", "2D bLidar"))
        self.label_3.setText(_translate("Form", "Real Sense"))
        self.label_4.setText(_translate("Form", "Dynamixel (Head)"))
        self.pushButton.setText(_translate("Form", "Launch"))
        self.radioButton_8.setText(_translate("Form", "True"))
        self.radioButton_7.setText(_translate("Form", "False"))
        self.radioButton_5.setText(_translate("Form", "True"))
        self.radioButton_6.setText(_translate("Form", "False"))
        self.radioButton_3.setText(_translate("Form", "True"))
        self.radioButton_4.setText(_translate("Form", "False"))
        self.radioButton_2.setText(_translate("Form", "True"))
        self.radioButton.setText(_translate("Form", "False"))
